package com.example.lab.pojo;

public enum ResultMessage {
    EXIST,
    NOTFOUND,
    SUCCESS,
    SUCCESS_LOGIN_ADMIN,
    SUCCESS_LOGIN_TEACHER,
    SUCCESS_LOGIN_TEACHER_RESETPASSWORD,
    SUCCESS_LOGIN_STUDENT,
    SUCCESS_LOGIN_STUDENT_RESETPASSWORD,
    FAILED,
    NOT_OPEN
}
